### ISSUE TITLE
connection protocol not supported

### ISSUE THREAD

**Issue by IgorDePaula** [dresende/node-orm2#327]
I copied and pasted the example on first page and the app throw this exception 

if (err) throw err;
                 ^
Error: CONNECTION_PROTOCOL_NOT_SUPPORTED
    at Object.defineProperty.value (/home/icarvalho/node_modules/orm/lib/ErrorCodes.js:12:13)
    at Object.exports.connect (/home/icarvalho/node_modules/orm/lib/ORM.js:129:32)
    at Object.<anonymous> (/home/icarvalho/Área de Trabalho/nodeorm/app.js:3:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by qqstar** [comment]
npm update
npm install mysql

**Comment by iaincollins** [comment]
Obvious but small tip that might folks who land here scratching their heads about what this is suddenly happening, if you get this after upgrading between node versions (e.g. 6/7/8) and run into this error when it previously working for you, deleting your **node_modules** folder and running `npm install` may resolve it for you.

**Comment by IgorDePaula** [comment]
@iaincollins this issue is closed, the date is from 2013.

**Comment by iaincollins** [comment]
@IgorDePaula I know. It's normal on GitHub to update popular problems with solutions, including closed issues that have new triggers.
