### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by AlexKhodaverdian** [dresende/node-orm2#668]
After running this code:
app.get('/', function (req, res) {
  req.models.smile.create({ space: "John", title: "Doe", story: "helo", happiness_level:5, like_count: 10, created_at: 10, updated_at:10 })
  req.models.smile.find(function(err, smiles){console.log(smiles[3].id)})
  res.send('Hello World!');
});

And visiting '/' my page loads fine, but the application crashes. Output: 
/Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Model.js:569
				return cb(null, single ? Instances[0] : Instances);
				       ^

TypeError: cb is not a function
    at createNext (/Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Model.js:569:12)
    at /Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Model.js:591:6
    at /Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:619:12
    at Instance.saveInstanceExtra (/Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:341:19)
    at /Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:190:5
    at Instance.runAfterSaveActions (/Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:143:3)
    at finish (/Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:188:4)
    at Instance.saveAssociations (/Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:336:11)
    at /Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Instance.js:214:11
    at /Users/armenkhodaverdian/Documents/cs169/smile_cs169/backend/node_modules/orm/lib/Drivers/DML/postgres.js:221:10

**Comment by AlexKhodaverdian** [comment]
I believe it has to do with the create line

**Comment by AlexKhodaverdian** [comment]
No callback, of course
