### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by olee** [dresende/node-orm2#739]
Got the following crash report from orm - don't know much more information yet.

Will update this issue once I know more.

````
/home/development/node/..../node_modules/orm/lib/Model.js:270
            throw new ORMError("Model.get() IDs number mismatch (" + opts.keys.length + " needed, " + ids.length + " passed)", 'PARAM_MISMATCH', { model: opts.table });
            ^
ORMError: Model.get() IDs number mismatch (1 needed, 0 passed)
    at Function.Model.model.get (/home/development/node/..../node_modules/orm/lib/Model.js:270:13)
    at getCachedUser (/home/development/node/..../dist/common/core/authentication.js:15:28)
    at Context_1.default.DeviceLogin.one (/home/development/node/..../dist/common/core/authentication.js:46:16)
    at /home/development/node/..../node_modules/orm/lib/Model.js:460:11
    at /home/development/node/..../node_modules/orm/lib/ChainFind.js:213:72
    at /home/development/node/..../node_modules/orm/lib/Singleton.js:34:10
    at bound DeviceLogin.<anonymous> (/home/development/node/..../node_modules/orm/lib/Model.js:124:12)
    at /home/development/node/..../node_modules/orm/lib/Instance.js:28:7
    at Array.map (native)
    at Instance.emitEvent (/home/development/node/..../node_modules/orm/lib/Instance.js:27:17)
````

**Comment by olee** [comment]
Ok please ignore this - I didn't fully check what was going on :sweat:
