### ISSUE TITLE
Rethrow non-MySQL errors

### ISSUE THREAD

**Issue by akshaykumar12527** [dresende/node-orm2#814]
Can you please look into this i getting this error 

/root/project_name/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: cb is not a function
    at Query._callback (/root/project_name/node_modules/orm/lib/Drivers/DML/mysql.js:238:14)
    at Query.Sequence.end (/root/api.oyestar.com/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/root/api.oyestar.com/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/root/api.oyestar.com/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/root/project_name/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/root/project_name/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/project_name/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)

**Comment by dxg** [comment]
There is not enough information here to investigate.
It sounds like code somewhere didn't provide a callback.
