### ISSUE TITLE
 Cannot read property 'mapsTo' of undefined

### ISSUE THREAD

**Issue by TongDaDa** [dresende/node-orm2#834]
Use my SQL tool to query it as follows

![screen shot 2018-07-16 at 3 33 56 pm](https://user-images.githubusercontent.com/23241188/42747148-b3e32ca2-890d-11e8-9455-59cbf850104a.png)

But use "orm"  an unknown error has occurred 

``` javascript
TypeError: Cannot read property 'mapsTo' of undefined
    at Object.exports.transformOrderPropertyNames (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/Utilities.js:330:37)
    at chainRun (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/ChainFind.js:31:23)
    at Object.run (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/ChainFind.js:224:7)
    at Function.Model.model.find (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/Model.js:441:13)
    at generateAudio (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/controller/v1/generateAudio.js:19:36)
    at Layer.handle [as handle_request] (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/layer.js:95:5)
    at next (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/route.js:137:13)
    at Route.dispatch (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/layer.js:95:5)
    at /Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/index.js:281:22
    at Function.process_params (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/index.js:335:12)
    at next (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/index.js:275:10)
    at Function.handle (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/index.js:174:3)
    at router (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/layer.js:95:5)
    at trim_prefix (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_express@4.16.3@express/lib/router/index.js:317:13)
TypeError: Cannot read property 'mapsTo' of undefined
    at Object.exports.transformOrderPropertyNames (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/Utilities.js:330:37)
    at chainRun (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/ChainFind.js:31:23)
    at Object.run (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/ChainFind.js:224:7)
    at Function.Model.model.find (/Applications/XAMPP/xamppfiles/htdocs/woeks/striving/word_word_pronounced/node_modules/_orm@5.0.2@orm/lib/Model.js:441:13)

```

**Comment by dxg** [comment]
Without code showing how this can be reproduced, this can't be fixed.

**Comment by TongDaDa** [comment]
@dxg  sorry, I forgot it...  


``` javascript

    req.models.new_word_manage.where(`SELECT * FROM new_word_manage WHERE create_time BETWEEN "2018-07-15" AND "2018-07-16"`, (err, word) => {
            if (err) throw err;
            console.log(word);
            res.send("asdasd")
        });
```
